// Pavel Gornostaev <https://github.com/Pavreally>

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "Data/AITCSCoreData.h"
#include "Engine/DataAsset.h"
#include "Graph/AITCSCompiledTacticalGraph.h"

#include "AITCSTacticalFeatureTypes.generated.h"

/** Current tactical evaluation context passed to evaluators during a director pass. */
USTRUCT(BlueprintType)
struct AITCSRUNTIME_API FAITCSTacticalEvaluationContext
{
	GENERATED_BODY()

	FAITCSTacticalEvaluationContext();

	const FAITCSCompiledTacticalGraph* GetCompiledGraph() const;
	bool HasCompiledGraph() const;

	const FAITCSCompiledTacticalGraph* CompiledGraph = nullptr;

	/** Snapshot of the current tactical context at evaluation time. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "AITCS|Evaluation")
	FAITCSTacticalContextSnapshot Snapshot;

	/** World time at the moment of evaluation. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "AITCS|Evaluation")
	float WorldTimeSeconds = 0.0f;

	/** Delta time since the last evaluation pass. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "AITCS|Evaluation")
	float DeltaSeconds = 0.0f;

	/** Evaluation frame counter for ordering and reuse. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "AITCS|Evaluation")
	int32 EvaluationFrame = 0;
};

/** Order proposal generated by an evaluator during tactical evaluation. */
USTRUCT(BlueprintType)
struct AITCSRUNTIME_API FAITCSTacticalOrderProposal
{
	GENERATED_BODY()

	FAITCSTacticalOrderProposal();

	/** Unique identifier for this proposal. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Proposal", meta = (IgnoreForMemberInitializationTest))
	FGuid ProposalId;

	/** Name of the evaluator that created the proposal. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Proposal")
	FName EvaluatorName = NAME_None;

	/** Feature tag associated with this proposal's origin. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Proposal")
	FGameplayTag FeatureTag;

	/** Proposal tag used for filtering and decision matching. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Proposal")
	FGameplayTag ProposalTag;

	/** Additional tags describing the proposal semantics. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Proposal")
	FGameplayTagContainer ProposalTags;

	/** Tactical order recommended by this evaluator. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Proposal")
	FAITCSTacticalOrder Order;

	/** Priority used to compare proposals during selection. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Scoring")
	float Priority = 0.0f;

	/** Raw score assigned by the evaluator. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Scoring")
	float Score = 0.0f;

	/** Confidence in the proposal, normalized from 0.0 to 1.0. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Scoring", meta = (ClampMin = "0.0", ClampMax = "1.0", UIMin = "0.0", UIMax = "1.0"))
	float Confidence = 1.0f;

	/** Debug text describing why this proposal was created. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Debug", meta = (MultiLine = true))
	FString DebugReason;

	bool IsDispatchable() const;
	float GetWeightedScore(float EvaluatorWeight) const;
	void PrepareForDispatch();
};

USTRUCT(BlueprintType)
struct AITCSRUNTIME_API FAITCSTacticalEvaluatorRegistration
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Evaluator")
	FName EvaluatorName = NAME_None;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Evaluator")
	FGameplayTag FeatureTag;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Evaluator")
	bool bEnabled = true;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Evaluator")
	int32 SortPriority = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Evaluator", meta = (ClampMin = "0.0", UIMin = "0.0"))
	float Weight = 1.0f;
};

UCLASS(Abstract, BlueprintType)
class AITCSRUNTIME_API UAITCSTacticalFeatureConfig : public UDataAsset
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Feature")
	FGameplayTag FeatureTag;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Feature")
	bool bEnabled = true;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Feature")
	FAITCSTacticalEvaluatorRegistration EvaluatorDefaults;
};

USTRUCT(BlueprintType)
struct AITCSRUNTIME_API FAITCSTacticalRegisteredEvaluator
{
	GENERATED_BODY()

	UPROPERTY(Transient, VisibleAnywhere, BlueprintReadOnly, Category = "AITCS|Evaluator")
	TObjectPtr<UObject> EvaluatorObject = nullptr;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AITCS|Evaluator")
	FAITCSTacticalEvaluatorRegistration Registration;
};

USTRUCT(BlueprintType)
struct AITCSRUNTIME_API FAITCSTacticalEvaluatorReport
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "AITCS|Evaluator")
	FName EvaluatorName = NAME_None;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "AITCS|Evaluator")
	FGameplayTag FeatureTag;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "AITCS|Evaluator")
	bool bEnabled = false;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "AITCS|Evaluator")
	int32 ProposalsGenerated = 0;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "AITCS|Evaluator")
	int32 ProposalsAccepted = 0;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "AITCS|Evaluator")
	float EvaluationTimeSeconds = 0.0f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "AITCS|Debug")
	FString DebugSummary;
};
